---
 - hosts: tomcat
   remote_user: vagrant
   become: true
   become_method: sudo
   become_user: root
   gather_facts: true
   tasks:
#    - include_vars: defaults/main.yml
     - include: tasks/tomcat.yml
#    - include: tasks/mysql.yml
#    - include: tasks/php.yml
