- name: Add php repository
  apt_repository:
   repo: ppa:ondrej/php
   state: present
- name: Install php
  apt: name={{item}} state=present update_cache=yes
  with_items:
   - libapache2-mod-php5
   - php5-mcrypt
   - php5-curl
   - php5-gd
   - php5-xmlrpc
- name: Test PHP installation
  copy:
   src: ../tests/info.php
   dest: /var/www/html/info.php
   mode: 0644
- name: Restart Apache to test installation
  service:
   name: apache2
   state: restarted
