- name: Install tomcat7 with additional packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
   - tomcat7
   - tomcat7-docs
   - tomcat7-admin
   - tomcat7-examples
   - default-jdk
   - git
   - ant
- name: Check Installation
  service:
   name: tomcat7
   state: started
