- name: Install Atom | add repo
  apt_repository:
   repo: ppa:webupd8team/atom
   state: present
   update_cache: yes
- name: Install Atom
  apt: name=atom state=present update_cache=yes
- name: Install VScode |  with ubuntu-make
  shell: "umake ide visual-studio-code -y"
- name: Install Sublime texteditor | add repo
  apt_repository:
    repo: ppa:webupd8team/sublime-text-2
    state: present
- name: Install Sublime texteditor | Installation
  apt: name=sublime-text state=present update_cache=yes
- name: Install Gimp
  apt: name=gimp state=present update_cache=yes
