- name: Import Public key for community edition
  apt_key:
   keyserver: hkp://keyserver.ubuntu.com:80
   id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
- name: Add repository
  apt_repository:
   # filename: '/etc/apt/sources.list.d/mongodb-org-3.6.list'
   repo: 'deb https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.6 multiverse'
   state: present
   update_cache: yes
- name: Install MongoDB
  apt:
   name: mongodb-org
   state: present
   update_cache: yes
- name: mongodb-org is running
  service:
   name: mongod
   state: started

