- name: Install JDK | add repository
  apt_repository:
   repo: ppa:webupd8team/java
   state: present
   update_cache: yes
- name: Install JDK | Auto accept Oracle License
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    value: true
    vtype: select
- name: Install JDK | Install jdk
  apt: name={{ item }} state=present update_cache=yes
  with_items:
   - oracle-java8-installer
   - oracle-java8-set-default

