---
 - hosts: java
   remote_user: vagrant
   become: true
   become_method: sudo
   become_user: root
   gather_facts: true
   tasks:
     - include: tasks/jdk.yml
#     - include: tasks/gnome-desktop.yml
#     - include: tasks/eclipse.yml
