---
 - hosts: java
   remote_user: vagrant
   become: true
   become_method: sudo
   become_user: root
   gather_facts: true
   tasks:
     - include_vars: defaults/main.yml
     - include: tasks/jdk.yml
     - include: tasks/xfce-desktop.yml
     - include: tasks/utilities.yml
     - include: tasks/eclipse.yml
