---
 - hosts: lamp
   remote_user: vagrant
   become: true
   become_method: sudo
   become_user: root
   tasks:
   - include: tasks/pre-requisites.yml
   - include: tasks/apache.yml
   - include: tasks/mysql.yml
   - include: tasks/php.yml
